<?php

use Automattic\WooCommerce\Blocks\Payments\Integrations\AbstractPaymentMethodType;

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

/**
 * Everydaymoney Payment Gateway Blocks Integration.
 *
 * @since 1.3.0
 */
final class WC_Everydaymoney_Blocks_Integration extends AbstractPaymentMethodType {
    
    private $gateway;
    protected $name = 'everydaymoney_gateway';

    /**
     * Initializes the integration.
     */
    public function initialize() {
        $this->settings = get_option( 'woocommerce_everydaymoney_gateway_settings', [] );
        $gateways       = WC()->payment_gateways->get_available_payment_gateways();
        if ( isset( $gateways[ $this->name ] ) ) {
            $this->gateway = $gateways[ $this->name ];
        }
    }

    /**
     * Returns an array of script handles to enqueue for the payment method.
     * This is the crucial part that loads our new JavaScript file.
     *
     * @return string[]
     */
    public function get_payment_method_script_handles() {
        // 1. Register the script.
        // The `wp_register_script` function is used to tell WordPress about our script.
        // The asset file (`.asset.php`) is generated by the build process and contains
        // dependencies and version info.
        $script_path       = EVERYDAYMONEY_GATEWAY_PLUGIN_URL . 'assets/js/checkout.js';
        $script_asset_path = EVERYDAYMONEY_GATEWAY_PLUGIN_DIR . 'assets/js/checkout.asset.php';
        $script_asset      = file_exists( $script_asset_path )
            ? require( $script_asset_path )
            : array(
                'dependencies' => array(),
                'version'      => EVERYDAYMONEY_GATEWAY_VERSION,
            );
        
        wp_register_script(
            'wc-everydaymoney-blocks-integration',
            $script_path,
            $script_asset['dependencies'],
            $script_asset['version'],
            true
        );

        // 2. Return the handle of the registered script.
        // WooCommerce Blocks will then enqueue this script on the checkout page.
        return [ 'wc-everydaymoney-blocks-integration' ];
    }

    /**
     * Returns an array of key=>value pairs of data made available to the payment method script.
     *
     * @return array
     */
    public function get_payment_method_data() {
        if ( ! $this->gateway ) {
            return [];
        }

        return [
            'title'       => $this->get_setting( 'title' ),
            'description' => $this->get_setting( 'description' ),
            'supports'    => array_filter( $this->gateway->supports, [ $this->gateway, 'supports' ] ),
        ];
    }
}